/* Database schema to keep the structure of entire database. */



CREATE DATABASE vet_clinic; -- Create the database

CREATE TABLE animals (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(100) NOT NULL,
    date_of_birth DATE NOT NULL,
    escape_attempts INT NOT NULL,
    neutered BOOLEAN NOT NULL,
    weight_kg DECIMAL NOT NULL,
    PRIMARY KEY (id)
);

--add a column species_id to the animals tables
ALTER TABLE animals ADD COLUMN species VARCHAR(30);

-- Create a table named owners 
CREATE TABLE owners (
    id INT GENERATED ALWAYS AS IDENTITY,
    full_name VARCHAR(50) NOT NULL,
    age INT NOT NULL,
    PRIMARY KEY (id)
);


-- Create a table named species
CREATE TABLE species (
    id INT GENERATED ALWAYS AS IDENTITY,
    name VARCHAR(50) NOT NULL,
    PRIMARY KEY (id)
);

-- Modify animals table:
ALTER TABLE animals DROP COLUMN species;

ALTER TABLE animals DROP COLUMN id;

ALTER TABLE animals ADD COLUMN id INT GENERATED ALWAYS AS IDENTITY, ADD PRIMARY KEY (id);

-- Add column species_id which is a foreign key referencing species table
ALTER TABLE animals ADD COLUMN species_id INT;
ALTER TABLE animals ADD FOREIGN KEY (species_id) REFERENCES species (id);

-- Add column owner_id which is a foreign key referencing the owners table
ALTER TABLE animals ADD COLUMN owner_id INT;
ALTER TABLE animals ADD FOREIGN KEY (owner_id) REFERENCES owners (id);

--creating table name vets
CREATE TABLE vets (
      id INT GENERATED BY DEFAULT AS IDENTITY 
    (START WITH 1 INCREMENT BY 1) NOT NULL PRIMARY KEY,
    name VARCHAR(100),
    age INT,
    date_of_graduation DATE
);

--creating specialization table
CREATE TABLE specializations (
      species_id INT NOT NULL  REFERENCES species(id),
      vet_id INT NOT NULL   REFERENCES vets(id),
      PRIMARY KEY( species_id,vet_id) 
);

--creating visits table
CREATE TABLE visits (
      animal_id INT NOT NULL   REFERENCES animals(id),
      vet_id INT NOT NULL  REFERENCES vets(id),
      visit_date DATE NOT NULL   
);



